# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  tests_go:
    docker:
      - image: circleci/golang:1.13.0
        environment:
          GOPATH: /go
    working_directory: /repos/github.com/Jac0bDeal/chip-8/go
    steps:
      - checkout
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: git status
      - run:
          name: Run tests
          command: |
            trap "/go/bin/go-junit-report <test-results/golang/go-test.out > test-results/golang/go-test-report.xml" EXIT
            make test | tee test-results/golang/go-test.out
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: /go/src/github.com/Jac0bDeal/chip-8/go/test-results
          destination: test-results

  build_go:
    docker:
      - image: circleci/golang:1.13.0
    working_directory: /repos/github.com/Jac0bDeal/chip-8/go
    steps:
      - checkout
      - run:
          name: Build go binaries
          command: |
            export GOPATH=/go
            make all

