# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  tests_go:
    docker:
      - image: circleci/golang:1.13.0
        environment:
          GOPATH: "/go"
          GO111MODULE: "on"
    working_directory: /go/src/github.com/Jac0bDeal/chip-8/go
    steps:
      - checkout
      - run:
          name: Install go-junit-report
          command: go get -u github.com/jstemmer/go-junit-report
      - run:
          name: Run tests
          command: |
            cd go
            trap "/go/bin/go-junit-report <test-results/golang/go-test.out > test-results/golang/go-test-report.xml" EXIT
            make test | tee test-results/golang/go-test.out
            go tool cover -html=c.out -o coverage.html
            mkdir -p /tmp/artifacts
            my coverage.html /tmp/artifacts
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: /go/src/github.com/Jac0bDeal/chip-8/go/test-results
          destination: test-results
      - store_artifacts:
          path: /tmp/artifacts

  build_go:
    docker:
      - image: circleci/golang:1.13.0
        environment:
          GOPATH: "/go"
          GO111MODULE: "on"

    working_directory: /go/src/github.com/Jac0bDeal/chip-8/go
    steps:
      - checkout
      - run:
          name: Build go binaries
          command: |
            cd go
            make all

workflows:
  version: 2
  go_workflow:
    jobs:
    - tests_go
    - build_go:
        requires:
          - tests_go
